parent_cfg: configs/gefu/dtu_pretrain.yaml
exp_name: dtu_ft_scan103
gefu:
    test_input_views: 4
train_dataset:
    scene: scan103
test_dataset:
    scene: scan103
train:
    epoch: 222 # pretrained epoch + 6
    lr: 5e-5
save_ep: 1
eval_ep: 1
