parent_cfg: configs/gefu/dtu_pretrain.yaml
exp_name: dtu_ft_scan21
gefu:
    test_input_views: 4
train_dataset:
    scene: scan21
test_dataset:
    scene: scan21
train:
    epoch: 222 # pretrained epoch + 6
    lr: 5e-6
save_ep: 1
eval_ep: 1
    