parent_cfg: configs/gefu/dtu_pretrain.yaml
exp_name: dtu_ft_scan1
gefu:
    test_input_views: 4
train_dataset:
    scene: scan1
test_dataset:
    scene: scan1
train:
    epoch: 222 # pretrained epoch + 6
save_ep: 1
eval_ep: 1
   