parent_cfg: configs/gefu/llff_eval.yaml
exp_name: llff_ft_room

gefu:
    test_input_views: 4
    train_input_views: [3, 4]
    train_input_views_prob: [0.4, 0.6]
    cas_config:
        render_if: [True, True]
train_dataset:
    scene: room
test_dataset:
    scene: room
train:
    epoch: 222 # pretrained epoch + 6
    lr: 1e-3 
    sampler_meta:
        input_views_num: [3, 4] 
        input_views_prob: [0.4, 0.6]
save_ep: 1
eval_ep: 1
