parent_cfg: configs/gefu/dtu_pretrain.yaml

train_dataset_module: lib.datasets.nerf.gefu
test_dataset_module: lib.datasets.nerf.gefu

gefu:
    reweighting: True
    cas_config:
        render_if: [True, True]

train_dataset:
    data_root: 'nerf_synthetic'
    split: 'train'
    # input_h_w: [800, 800] # OOM for RTX 3090
    input_h_w: [512, 640]
    batch_size: 1
    input_ratio: 1.

test_dataset:
    data_root: 'nerf_synthetic'
    split: 'test'
    input_h_w: [800, 800]
    batch_size: 1
    input_ratio: 1.


